const tokenEl = document.getElementById('token');
const serverEl = document.getElementById('server');
const statusEl = document.getElementById('status');
const saveBtn = document.getElementById('save');

// Load — token auto-generated by background.js on first run
chrome.storage.local.get(['daedalus-token', 'daedalus-server'], (data) => {
  tokenEl.value = data['daedalus-token'] || '(generating...)';
  serverEl.value = data['daedalus-server'] || '';
  updateStatus(data['daedalus-token'] || '');
  // If no token yet, poll until background generates it
  if (!data['daedalus-token']) {
    const poll = setInterval(() => {
      chrome.storage.local.get(['daedalus-token'], (d) => {
        if (d['daedalus-token']) {
          clearInterval(poll);
          tokenEl.value = d['daedalus-token'];
          updateStatus(d['daedalus-token']);
        }
      });
    }, 500);
  }
});

// Save
saveBtn.addEventListener('click', () => {
  const token = tokenEl.value.trim();
  const server = serverEl.value.trim();
  chrome.storage.local.set({
    'daedalus-token': token,
    'daedalus-server': server,
  }, () => {
    updateStatus(token);
    // Ping the server to verify — but only once there is a server to ping.
    // Saving a blank URL previously fired a relative request at the options
    // page itself and reported the resulting failure as "Server unreachable".
    if (!server) {
      setStatus('err', 'Set a bridge URL — nothing will connect until you do');
      return;
    }
    if (token) {
      fetch(server + '/tabs', { headers: { 'Authorization': 'Bearer ' + token } })
        .then(r => r.ok ? r.json() : Promise.reject(r.status))
        .then(() => setStatus('ok', 'Connected — token saved'))
        .catch(e => setStatus('err', 'Server unreachable: ' + e));
    }
  });
});

function updateStatus(token) {
  if (token) {
    setStatus('ok', 'Token: ' + token.substring(0, 8) + '...');
  } else {
    setStatus('info', 'Not configured');
  }
}

function setStatus(type, msg) {
  statusEl.className = 'status ' + type;
  statusEl.textContent = msg;
}
