"""Every guard arm in the two launch-audit analysers, and its state.

A guard arm with no row that fails when it is deleted is UNDRIVEN:
deleting it leaves the suite green, and the change it makes to a real
source file is invisible to CI. So every arm here is in exactly one of
three states, and no fourth:

CONTROLLED - a row, or a control in ARM_CONTROLS below, that fails when
the arm is deleted. `evidence` names it.
REDUNDANT - the arm cannot change any verdict because a named other arm
or bound already decides. `evidence` names that bound.
DEAD - no input reaches it, and `evidence` is the argument why.

"Live and deliberately unpinned" is not a fourth state; it was withdrawn.
Every arm in this list was classified by DELETING it from the real
analyser in a worktree and re-asking every row and every probe shape,
not by reading it. The arms the two row files could not express are the
three in ARM_CONTROLS, which assert sites AND refusals rather than the
one-refusal shape a LAUNCH_REFUSAL_ROW is built for, and the two the
step ceiling names, whose mutants do not answer wrong but do not
stop, so there is no verdict for a row to hold.

`line` is where the arm was classified, `cut` is the one clause the
sweep deleted (`op:line[:arg]`, which `tests/_arm_sweep.py` replays),
and `anchor` is the text of the arm's own block, so a reader can find it
and a test can notice it moving.
"""
CONTROLLED = 'CONTROLLED'
REDUNDANT = 'REDUNDANT'
DEAD = 'DEAD'
STATES = (CONTROLLED, REDUNDANT, DEAD)


ARM_CONTROLS = (
    ('subprocess-member-run-receiver',
     ("import subprocess\nsubprocess.Popen(['git', "
      "'status']).wait(timeout=30)\n"), [(2, 'unreadable', 'unplaced')],
     ([
      'subprocess-member-run-receiver:2 calls through a receiver the audit '
      'cannot resolve',
      'subprocess-member-run-receiver:2 does not fail loudly on a failed '
      'git command',
      'subprocess-member-run-receiver:2 launches through subprocess.Popen, '
      'which the audit does not see',
      ])),
    ('eval-receiver-is-unresolved',
     ("import subprocess\nsubprocess.run(['git', 'status'], "
      "check=True)\neval('x').run(['git', 'status'], check=True, "
      'timeout=30)\n'), [(3, 'unreadable', 'unplaced')],
     ([
      'eval-receiver-is-unresolved:3 calls through a receiver the audit '
      'cannot resolve',
      'eval-receiver-is-unresolved:3 calls eval, which the audit cannot '
      'resolve',
      ])),
    ('call-func-receiver-is-unresolved',
     ("import subprocess\ndef f():\n    return str\nf()().upper(['git', "
      "'status'], timeout=30)\n"), [(4, 'unreadable', 'unplaced')],
     ([
      'call-func-receiver-is-unresolved:4 calls through a receiver the '
      'audit cannot resolve',
      'call-func-receiver-is-unresolved:4 calls through a receiver the '
      'audit cannot resolve',
      'call-func-receiver-is-unresolved declares no launch the audit can '
      'see through "subprocess" or a binding derived from it',
      ])),
)

# The one control that asserts no verdict: its arm's mutant
# does not answer wrong, it does not stop, so there is nothing
# for a row to hold and the bound is a step count instead.
STEP_CEILING_CONTROL = 'fixpoint-terminates-with-a-launcher-factory'

LAUNCH_ARMS = (
    ('par.comprehension', '_launch_audit.py', 41, 'drop_if:41',
     "if args is None: return {getattr(target, 'id', None) for generator...",
     'args is None: a comprehension binds its loop names', 'CONTROLLED',
     'comprehension-target-receiver-is-reported'),
    ('par.vararg-kwarg', '_launch_audit.py', 50, 'drop_stmt:50',
     'for extra in (args.vararg, args.kwarg): if extra is not None:...',
     'a vararg/kwarg name is a parameter for the receiver resolver',
     'CONTROLLED',
     'kwarg-receiver-shadowing-a-module-import-is-unproved'),
    ('norm.no-dot', '_launch_audit.py', 73, 'drop_if:73',
     "if not called or '.' not in called: return called",
     'a callee with no dot is returned verbatim', 'CONTROLLED',
     'annotated-subprocess-alias-is-unproved'),
    ('norm.alias', '_launch_audit.py', 77, 'drop_if:77',
     "if canonical: return f'{canonical}.{member}'",
     'a machinery alias maps to its canonical name', 'CONTROLLED',
     'aliased-machinery-member-call'),
    ('callee.attribute-on-name', '_launch_audit.py', 83, 'drop_if:83',
     'if isinstance(call.func, ast.Attribute) \\ and isinstance(call.func...',
     'a.b is a spellable callee', 'CONTROLLED',
     'call-on-a-name-the-analyser-can-name-is-still-proved'),
    ('callee.bare-name', '_launch_audit.py', 86, 'drop_if:86',
     'if isinstance(call.func, ast.Name): return call.func.id',
     'a bare name is a spellable callee', 'CONTROLLED',
     'dunder-import-launch'),
    ('drv.name', '_launch_audit.py', 92, 'drop_if:92',
     "if isinstance(value, ast.Name): return (value.id == 'subprocess' o...",
     'a Name deriving: subprocess / bound / factory', 'CONTROLLED',
     'bound-name-called-bare-is-a-placed-launch'),
    ('drv.attribute', '_launch_audit.py', 95, 'drop_if:95',
     'if isinstance(value, ast.Attribute): return derives(value.value,...',
     'an Attribute derives as its base', 'CONTROLLED',
     'launcher-factory-bare-name-receiver-is-a-placed-launch'),
    ('drv.namedexpr', '_launch_audit.py', 97, 'drop_if:97',
     'if isinstance(value, ast.NamedExpr): return derives(value.value,...',
     'a walrus target derives as its value', 'CONTROLLED',
     'walrus-value-derives-into-a-placed-launch'),
    ('drv.sequence', '_launch_audit.py', 99, 'drop_if:99',
     'if isinstance(value, (ast.Tuple, ast.List, ast.Set)): return any(d...',
     'a tuple/list/set derives if an elt does', 'CONTROLLED',
     'list-target-subprocess-assignment'),
    ('drv.dict', '_launch_audit.py', 101, 'drop_if:101',
     'if isinstance(value, ast.Dict): return any(derives(item, bound)',
     'a dict derives if a value does', 'CONTROLLED',
     'dict-value-receiver-is-placed'),
    ('drv.comprehension', '_launch_audit.py', 104, 'drop_if:104',
     'if isinstance(value, (ast.ListComp, ast.SetComp, ast.GeneratorExp)...',
     'a comprehension derives as elt or iter', 'CONTROLLED',
     'generator-expression-receiver-is-placed'),
    ('drv.dictcomp', '_launch_audit.py', 108, 'drop_if:108',
     'if isinstance(value, ast.DictComp): return (derives(value.key,...',
     'a dict comprehension derives key/value/iter', 'CONTROLLED',
     'dict-comprehension-receiver-is-placed'),
    ('drv.ifexp', '_launch_audit.py', 113, 'drop_if:113',
     'if isinstance(value, ast.IfExp): return derives(value.body, bound)...',
     'a conditional expression derives either side', 'CONTROLLED',
     'method-on-a-conditional-expression-is-a-placed-launch'),
    ('drv.lambda', '_launch_audit.py', 115, 'drop_if:115',
     'if isinstance(value, ast.Lambda): return derives(value.body,...',
     'a lambda derives as its body', 'CONTROLLED',
     'lambda-factory-receiver-is-placed'),
    ('drv.subscript', '_launch_audit.py', 117, 'drop_if:117',
     'if isinstance(value, ast.Subscript): base = value.value',
     'a subscript derives', 'CONTROLLED', 'exec-namespace-receiver-is-placed'),
    ('drv.subscript-sys-modules', '_launch_audit.py', 119, 'drop_if:119',
     'if isinstance(base, ast.Attribute) \\ and isinstance(base.value, as...',
     'sys.modules[...] always derives, whatever the key reads', 'CONTROLLED',
     'sys-modules-blanket-bound-to-a-name-is-placed'),
    ('drv.subscript-key-reads-subprocess', '_launch_audit.py', 123,
     'drop_if:123',
     "if reader.resolve_string(value.slice) == 'subprocess': return True",
     "a subscript key reading 'subprocess' derives", 'CONTROLLED',
     'exec-namespace-receiver-is-placed'),
    ('drv.subscript-base', '_launch_audit.py', 125, 'drop_stmt:125',
     'return derives(base, bound)',
     'otherwise the subscript derives as base', 'CONTROLLED',
     'method-on-a-subscript-of-a-derived-name'),
    ('drv.call', '_launch_audit.py', 126, 'drop_if:126',
     'if isinstance(value, ast.Call): called =...', 'a call derives',
     'CONTROLLED',
     'launcher-factory-bare-name-receiver-is-a-placed-launch'),
    ('drv.call-partial', '_launch_audit.py', 128, 'drop_if:128',
     'if called in partial_aliases and any( derives(arg, bound) for arg ...',
     'a partial of a derived value derives', 'CONTROLLED',
     'partial-of-a-derived-value-derives'),
    ('drv.call-import-module', '_launch_audit.py', 131, 'drop_if:131',
     'if called in import_module_aliases and any( reader.resolve_string(...',
     "an import_module naming 'subprocess' derives", 'CONTROLLED',
     'machinery-call-binding-with-a-readable-argument-is-read'),
    ('drv.call-getattr', '_launch_audit.py', 137, 'drop_if:137',
     "if called == 'getattr' and any( derives(arg, bound) for arg in val...",
     'a getattr of a derived value derives', 'CONTROLLED',
     'module-shadows-getattr-and-an-argument-derives'),
    ('drv.call-attribute-on-subprocess', '_launch_audit.py', 141,
     'drop_if:141',
     'if isinstance(value.func.value, ast.Name) \\ and value.func.value.i...',
     'subprocess.<anything> is not itself a derivation', 'CONTROLLED',
     'call-on-a-name-the-analyser-can-name-is-still-proved'),
    ('drv.call-attribute-other', '_launch_audit.py', 144, 'drop_stmt:144',
     'return derives(value.func.value, bound)',
     'a method call derives as its receiver', 'CONTROLLED',
     'method-call-derives-as-its-receiver'),
    ('drv.call-name-bound', '_launch_audit.py', 146, 'drop_if:146',
     'if (value.func.id in bound or value.func.id in module_factories): ...',
     'a call on a bound or factory name derives', 'CONTROLLED',
     'launcher-factory-bare-name-receiver-is-a-placed-launch'),
    ('drv.call-name-defined', '_launch_audit.py', 149, 'drop_if:149',
     'if value.func.id in defined_names: return False',
     'a call on a name this module defines does not derive', 'CONTROLLED',
     'call-on-a-name-this-module-defines-is-not'),
    ('drv.call-name-other', '_launch_audit.py', 151, 'drop_stmt:151',
     'return any(derives(arg, bound) for arg in value.args)',
     'a call on an unaccounted name derives if an argument does',
     'REDUNDANT',
     ('character-identical to `return any(derives(arg, bound) for arg in '
      'value.args)` at :164, which a bare-Name callee reaches once :157-163 '
      'has returned nothing')),
    ('drv.call-other-func', '_launch_audit.py', 152, 'drop_stmt:152',
     'return any(derives(arg, bound) for arg in value.args)',
     'a call whose func is not a Name/Attribute derives on its arguments',
     'CONTROLLED',
     'subscript-callee-derives-on-its-arguments'),
    ('drv.fallthrough', '_launch_audit.py', 153, 'drop_stmt:153',
     'return False', 'any other expression does not derive', 'REDUNDANT',
     ('every one of the 21 `derives(...)` call sites reads the result in a '
      'boolean position (`if`, `and`, `or`, `any(...)`) and none tests it '
      'with `is`, so an implicit None is indistinguishable from False')),
    ('res.attribute', '_launch_audit.py', 157, 'drop_if:157',
     'if isinstance(expr, ast.Attribute): return...',
     'an attribute resolves as its base', 'CONTROLLED',
     'attribute-chain-over-a-bound-name-is-unresolved'),
    ('res.subscript', '_launch_audit.py', 159, 'drop_if:159',
     'if isinstance(expr, ast.Subscript): base = expr.value',
     'a subscript resolves as its base', 'CONTROLLED',
     'sys-modules-negative-space'),
    ('res.subscript-sys-modules', '_launch_audit.py', 161, 'drop_if:161',
     'if isinstance(base, ast.Attribute) \\ and isinstance(base.value, as...',
     'a sys.modules subscript is never resolved safe', 'CONTROLLED',
     'sys-modules-negative-space'),
    ('res.subscript-base', '_launch_audit.py', 166, 'drop_stmt:166',
     'return resolves_safe(base)',
     'otherwise the subscript resolves as base', 'CONTROLLED',
     'a-subscript-over-a-bound-name-resolves-as-base'),
    ('res.call', '_launch_audit.py', 167, 'drop_if:167',
     'if isinstance(expr, ast.Call): called = callee_of(expr)',
     'a call receiver is judged by its callee', 'CONTROLLED',
     'receiver-through-getattr'),
    ('res.call-eval-exec', '_launch_audit.py', 169, 'drop_if:169',
     "if called in ('eval', 'exec'): return False",
     'eval/exec is never resolved safe', 'CONTROLLED',
     'eval-receiver-is-unresolved'),
    ('res.call-machinery', '_launch_audit.py', 171, 'drop_if:171',
     "if called == 'getattr' or called in partial_aliases \\ or called in...",
     'getattr / partial / import_module is never resolved safe',
     'CONTROLLED', 'receiver-through-getattr'),
    ('res.call-name', '_launch_audit.py', 174, 'drop_if:174',
     'if isinstance(expr.func, ast.Name): return expr.func.id in safe_na...',
     'a bare-name call resolves safe when the name is accounted and unbound',
     'CONTROLLED',
     'a-bare-name-call-receiver-resolves-safe'),
    ('res.call-attribute-name', '_launch_audit.py', 177, 'drop_if:177',
     'if isinstance(expr.func, ast.Attribute): if isinstance(expr.func.v...',
     'a method call is judged on its base', 'CONTROLLED',
     'a-run-result-receiver-without-a-plain-import'),
    ('res.call-attribute-bound', '_launch_audit.py', 180, 'drop_if:180',
     'if base in bound or base in module_factories: return False',
     'a method on a bound or factory name is not resolved safe',
     'CONTROLLED',
     'method-on-a-call-whose-base-is-safe-and-bound'),
    ('res.call-attribute-subprocess', '_launch_audit.py', 182, 'drop_if:182',
     "if base == 'subprocess': return expr.func.attr == 'run'",
     'only subprocess.run is resolved safe on the subprocess module',
     'CONTROLLED', 'subprocess-member-run-receiver'),
    ('res.call-attribute-safe', '_launch_audit.py', 184, 'drop_stmt:184',
     'return base in safe_names',
     'a method on a safe bare name is resolved safe', 'CONTROLLED',
     'a-method-on-an-undefined-base-is-unresolved'),
    ('res.call-attribute-other', '_launch_audit.py', 185, 'drop_stmt:185',
     'return resolves_safe(expr.func.value)',
     'a method on a non-bare receiver resolves as that receiver',
     'CONTROLLED',
     'an-attribute-chain-receiver-is-unresolved'),
    ('res.call-other-func', '_launch_audit.py', 186, 'drop_stmt:186',
     'return False',
     'a call whose func is not a Name/Attribute is not resolved safe',
     'CONTROLLED', 'call-func-receiver-is-unresolved'),
    ('res.name', '_launch_audit.py', 187, 'drop_if:187',
     'if isinstance(expr, ast.Name): return expr.id not in bound and exp...',
     'a bare name is resolved safe when unbound and not subprocess',
     'CONTROLLED',
     'a-bare-name-receiver-over-a-bound-name'),
    ('res.fallthrough', '_launch_audit.py', 189, 'drop_stmt:189',
     'return True', 'any other receiver is resolved safe', 'CONTROLLED',
     'dict-value-receiver-is-placed'),
    ('imp.subprocess-alias', '_launch_audit.py', 197, 'drop_if:197',
     "if alias.name == 'subprocess' and alias.asname:...",
     'an aliased subprocess import is a refusal and a subprocess name',
     'CONTROLLED', 'alias-import-unplaced'),
    ('imp.machinery', '_launch_audit.py', 202, 'drop_if:202',
     "elif alias.name in machinery and '.' not in alias.name: module_ali...",
     'an import of functools/importlib records a module alias', 'CONTROLLED',
     'aliased-machinery-member-call'),
    ('imp.dotted', '_launch_audit.py', 204, 'drop_if:204',
     "elif '.' in alias.name and not alias.asname:...",
     'a dotted unaliased import adds its top-level name as safe',
     'CONTROLLED',
     'a-dotted-import-contributes-its-top-level-name'),
    ('imp.plain', '_launch_audit.py', 208, 'drop_stmt:208',
     'safe_names.add(alias.asname or alias.name)',
     'any other import name is safe', 'CONTROLLED',
     'call-on-a-name-the-analyser-can-name-is-still-proved'),
    ('imp.from-subprocess', '_launch_audit.py', 210, 'drop_if:210',
     "if node.module == 'subprocess': subprocess_names.update(",
     'a from-import of subprocess is a refusal and a subprocess name',
     'CONTROLLED',
     'subprocess-from-import-spelled-then-rebound-is-unproved'),
    ('imp.from-partial', '_launch_audit.py', 218, 'drop_if:218',
     'if imported in partial_aliases: partial_aliases.add(alias.asname o...',
     'a from-import of partial records the alias', 'CONTROLLED',
     'receiver-through-partial-builtin-alias'),
    ('imp.from-import-module', '_launch_audit.py', 221, 'drop_if:221',
     'elif imported in import_module_aliases:...',
     'a from-import of import_module records the alias', 'CONTROLLED',
     'import-module-from-import-alias'),
    ('imp.from-plain', '_launch_audit.py', 226, 'drop_stmt:226',
     'safe_names.add(alias.asname or alias.name)',
     'any other from-import name is safe', 'CONTROLLED',
     'a-from-import-name-is-accounted'),
    ('imp.no-plain-import', '_launch_audit.py', 234, 'drop_if:234',
     'if not refusals and not any( isinstance(node, ast.Import) and any(...',
     'a module that never plainly imports subprocess is a refusal',
     'CONTROLLED', 'no-plain-import'),
    ('bind.assign', '_launch_audit.py', 246, 'drop_if:246',
     'if isinstance(node, ast.Assign): bindings.extend(',
     'an assignment target is a binding', 'CONTROLLED', 'ambiguous-name'),
    ('bind.annassign', '_launch_audit.py', 250, 'drop_if:250',
     'elif isinstance(node, ast.AnnAssign) and node.value \\ and isinstan...',
     'an annotated assignment is a binding', 'CONTROLLED',
     'annotated-assignment-target-is-a-binding'),
    ('bind.namedexpr', '_launch_audit.py', 253, 'drop_if:253',
     'elif isinstance(node, ast.NamedExpr): bindings.append((node.target...',
     'a walrus target is a binding', 'CONTROLLED',
     'walrus-target-is-a-binding'),
    ('bind.function', '_launch_audit.py', 255, 'drop_if:255',
     'elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):...',
     'a def names itself and reads its body', 'CONTROLLED',
     'launcher-factory-bare-name-receiver-is-a-placed-launch'),
    ('bind.function-default', '_launch_audit.py', 260, 'drop_stmt:260',
     'for arg, default in zip(args.args[-len(defaults):], defaults): bin...',
     'a positional default binds its parameter', 'CONTROLLED',
     'positional-default-binds-its-parameter'),
    ('bind.function-kwonly-default', '_launch_audit.py', 263,
     'drop_stmt:262',
     'if default is not None: bindings.append((arg.arg, default))',
     'a keyword-only default binds its parameter', 'CONTROLLED',
     'keyword-only-default-binds-its-parameter'),
    ('bind.function-returns', '_launch_audit.py', 265, 'drop_stmt:265',
     'returns.extend( (node.name, statement.value) for statement in ast....',
     'a def return is a factory value', 'CONTROLLED',
     'launcher-factory-bare-name-receiver-is-a-placed-launch'),
    ('bind.function-yields', '_launch_audit.py', 269, 'drop_stmt:269',
     'yields.extend( (node.name, statement.value) for statement in ast.w...',
     'a def yield is a factory value', 'CONTROLLED',
     'yielded-value-registers-a-module-factory'),
    ('bind.for-target', '_launch_audit.py', 275, 'drop_if:274',
     'if isinstance(node.target, ast.Name): bindings.append((node.target...',
     'a for target name binds the iterable', 'CONTROLLED',
     'argv-container-is-git-when-any-element-is'),
    ('bind.class', '_launch_audit.py', 277, 'drop_if:277',
     'elif isinstance(node, ast.ClassDef): defined_names.add(node.name)',
     'a class names itself', 'CONTROLLED',
     'class-body-assignment-binds-under-the-class'),
    ('bind.class-body-assign', '_launch_audit.py', 280, 'drop_if:280',
     'if isinstance(statement, ast.Assign): bindings.append((node.name,...',
     'a class body assignment binds under the class name', 'CONTROLLED',
     'class-body-assignment-binds-under-the-class'),
    ('bind.with-target', '_launch_audit.py', 284, 'drop_if:282',
     'if isinstance(item.optional_vars, ast.Name): bindings.append( (ite...',
     'a with target name binds the context', 'CONTROLLED',
     'with-target-name-binds-its-context'),
    ('tbl.ambiguous', '_launch_audit.py', 307, 'drop_if:307',
     'if name in binding_map: ambiguous.add(name)',
     'a name bound twice is ambiguous', 'CONTROLLED', 'ambiguous-name'),
    ('fx.bound-add', '_launch_audit.py', 341, 'drop_if:341',
     'if name not in bound and derives(value, bound): bound.add(name)',
     'a deriving binding is added to bound', 'CONTROLLED',
     'bound-name-called-bare-is-a-placed-launch'),
    ('fx.skip-registered', '_launch_audit.py', 345, 'drop_if:345',
     'if name in module_factories or name in launcher_factories:...',
     'an already-registered factory is not reconsidered', 'CONTROLLED',
     'fixpoint-terminates-with-a-launcher-factory'),
    ('fx.factory-derives', '_launch_audit.py', 347, 'drop_if:347',
     'if derives(value, bound): if isinstance(value, ast.Name):',
     'a factory value that derives is registered', 'CONTROLLED',
     'launcher-factory-bare-name-receiver-is-a-placed-launch'),
    ('fx.module-factory', '_launch_audit.py', 348, 'drop_if:348',
     'if isinstance(value, ast.Name): module_factories.add(name)',
     'a factory returning a bare Name is a module factory', 'CONTROLLED',
     'factory-origin-cannot-be-named-is-unproved'),
    ('fx.launcher-factory', '_launch_audit.py', 355, 'drop_span:355:357',
     'launcher_factories.add(name)',
     'a factory returning a non-Name is a launcher factory and is bound',
     'CONTROLLED',
     'launcher-factory-bare-name-receiver-is-a-placed-launch'),
    ('walk.safe-name', '_launch_audit.py', 360, 'drop_if:360',
     'if isinstance(node, ast.Name) \\ and isinstance(node.ctx, ast.Store...',
     'an unbound store name is accounted as safe', 'CONTROLLED',
     'call-on-a-name-the-analyser-can-name-is-still-proved'),
    ('walk.assign-derives', '_launch_audit.py', 364, 'drop_if:364',
     'if isinstance(node, (ast.Assign, ast.AnnAssign)) \\ and node.value ...',
     'a deriving assignment is walked', 'CONTROLLED',
     'annotated-attribute-target-subprocess-assignment'),
    ('walk.assign-tuple', '_launch_audit.py', 373, 'drop_if:373',
     'if any(isinstance(t, (ast.Tuple, ast.List)) for t in targets):...',
     'a tuple/list target unpacks values the audit cannot follow',
     'CONTROLLED', 'list-target-subprocess-assignment'),
    ('walk.assign-non-name', '_launch_audit.py', 378, 'drop_if:378',
     'elif not all(isinstance(t, ast.Name) for t in targets):...',
     'an attribute/subscript target binds where it cannot be followed',
     'CONTROLLED',
     'annotated-attribute-target-subprocess-assignment'),
    ('walk.for-non-name', '_launch_audit.py', 383, 'drop_if:383',
     'if isinstance(node, (ast.For, ast.AsyncFor)) \\',
     'a for target that is not a name', 'CONTROLLED',
     'subscript-for-target-subprocess-launch'),
    ('walk.for-tuple', '_launch_audit.py', 386, 'drop_if:386',
     'if isinstance(node.target, (ast.Tuple, ast.List)):...',
     'a tuple for target unpacks', 'CONTROLLED',
     'tuple-for-target-subprocess-launch'),
    ('walk.for-other', '_launch_audit.py', 391, 'drop_stmt:391',
     "refusals.append( f'{here}:{node.lineno} binds a subprocess-derived...",
     'a subscript for target binds', 'CONTROLLED',
     'subscript-for-target-subprocess-launch'),
    ('ch.eval-exec', '_launch_audit.py', 401, 'drop_if:401',
     "if called in ('eval', 'exec'): refusals.append(",
     'an eval/exec call is a refusal', 'CONTROLLED', 'eval-call'),
    ('ch.machinery-member', '_launch_audit.py', 408, 'drop_if:408',
     'if module in machinery \\ and member not in machinery[module]:...',
     'a machinery member the audit does not know is a refusal', 'CONTROLLED',
     'aliased-machinery-member-call'),
    ('ch.undefined-name', '_launch_audit.py', 413, 'drop_if:413',
     'if isinstance(func, ast.Name) \\ and not (func.id in bound or func....',
     'a callee name in none of the six accounts is a refusal', 'CONTROLLED',
     'undefined-callee-name'),
    ('ch.attribute-on-name', '_launch_audit.py', 422, 'drop_if:422',
     'if isinstance(func, ast.Attribute) \\ and isinstance(func.value, as...',
     'a method on subprocess or a bound name is a placed launch',
     'CONTROLLED', 'ambiguous-name'),
    ('ch.name-in-bound', '_launch_audit.py', 427, 'drop_if:427',
     'elif isinstance(func, ast.Name) and func.id in bound:...',
     'a bare name in bound is a placed launch', 'CONTROLLED',
     'bound-name-called-bare-is-a-placed-launch'),
    ('ch.namedexpr-in-bound', '_launch_audit.py', 434, 'drop_if:434',
     'elif isinstance(func, ast.NamedExpr) and func.target.id in bound:...',
     'a walrus target in bound is a placed launch', 'CONTROLLED',
     'walrus-target-in-bound-is-a-placed-launch'),
    ('ch.module-factory-call', '_launch_audit.py', 436, 'drop_if:436',
     'elif isinstance(func, ast.Attribute) \\ and isinstance(func.value, ...',
     'a method on a module-factory CALL is a placed launch', 'CONTROLLED',
     'method-on-a-module-factory-call-is-a-placed-launch'),
    ('ch.call-or-subscript', '_launch_audit.py', 441, 'drop_if:441',
     'elif isinstance(func, (ast.Call, ast.Subscript)): refusals.append(',
     'a callee that is itself a call or a subscript is a refusal',
     'CONTROLLED', 'callee-through-subscript'),
    ('ch.attribute-derives', '_launch_audit.py', 445, 'drop_if:445',
     'elif isinstance(func, ast.Attribute) \\ and not isinstance(func.val...',
     'a non-Name receiver that derives is a placed launch', 'CONTROLLED',
     'exec-namespace-receiver-is-placed'),
    ('ch.attribute-unresolved', '_launch_audit.py', 456, 'drop_if:456',
     'elif isinstance(func, ast.Attribute): unresolved = not resolves_sa...',
     'a non-Name receiver that does not resolve safe is a refusal',
     'CONTROLLED', 'receiver-through-getattr'),
    ('mr.not-a-call', '_launch_audit.py', 470, 'drop_if:470',
     'if not isinstance(held, ast.Call): return False',
     'a name not bound to a call is not machinery', 'CONTROLLED',
     'proved-name-receiver-is-not-reported'),
    ('mr.normalized-callee', '_launch_audit.py', 472, 'drop_if:472',
     'if normalize(callee_of(held)) in import_module_aliases: return...',
     'a call whose callee reads as import_module is machinery', 'CONTROLLED',
     'machinery-through-a-bare-alias-is-unproved'),
    ('mr.func-shape', '_launch_audit.py', 475, 'drop_if:475',
     'if not isinstance(func, ast.Attribute) \\ or not isinstance(func.va...',
     'anything but a method on a bare name is not machinery', 'CONTROLLED',
     'factory-origin-cannot-be-named-is-unproved'),
    # mr.while-guard: see ARM_NOTES in _launch_arm_records.
    ('mr.while-guard', '_launch_audit.py', 483, 'replace:483:while True:',
     'while base in binding_map and base not in seen \\ and base not in a...',
     'the base-following loop stops on an unheld, seen or ambiguous base',
     'CONTROLLED', STEP_CEILING_CONTROL),
    ('mr.target-not-name', '_launch_audit.py', 487, 'drop_if:487',
     'if not isinstance(target, ast.Name): return False',
     'a base bound to a non-Name is not machinery', 'CONTROLLED',
     'machinery-base-bound-to-a-call-is-not-machinery'),
    ('mr.return', '_launch_audit.py', 490, 'drop_stmt:490',
     "return f'{base}.{func.attr}' in import_module_aliases",
     'the followed base decides the verdict', 'CONTROLLED',
     'machinery-reached-by-assignment-is-unproved'),
    ('pf.not-a-name', '_launch_audit.py', 528, 'drop_if:528',
     'if not isinstance(receiver, ast.Name): return False',
     'only a bare name can be proved fixed', 'CONTROLLED',
     'conditional-class-body-attribute-is-reported'),
    ('pf.not-safe', '_launch_audit.py', 544, 'boolop:544:0',
     'if (receiver.id not in safe_names or receiver.id in bound or recei...',
     'a name the module never accounts is unreadable', 'CONTROLLED',
     'module-factory-name-receiver-stays-unplaced'),
    ('pf.in-bound', '_launch_audit.py', 545, 'boolop:544:1',
     "or receiver.id in subprocess_names or receiver.id == 'subprocess')...",
     'a bound name is not a proved receiver', 'DEAD',
     ('the unplaced loop only asks about a Call the chain did not place '
      '(:575 filters on `id(node) not in placed`), and every Call whose '
      'receiver is a Name in `bound` is placed by :411 or :416, or is '
      'refused at :510 first because the receiver it would carry is an '
      'Attribute')),
    ('pf.in-subprocess-names', '_launch_audit.py', 546, 'boolop:545:0',
     "or receiver.id == 'subprocess'): return False",
     'a rebound subprocess alias is not a proved receiver', 'CONTROLLED',
     'annotated-subprocess-alias-is-unproved'),
    ('pf.bare-subprocess', '_launch_audit.py', 546, 'boolop:546:0',
     "or receiver.id == 'subprocess'): return False",
     'the subprocess name itself is not proved', 'CONTROLLED',
     'bare-subprocess-receiver-is-unplaced'),
    ('pf.parameter', '_launch_audit.py', 551, 'drop_if:551',
     'if receiver.id in shadowed: return False',
     'a parameter is a different binding', 'CONTROLLED',
     'comprehension-target-receiver-is-reported'),
    ('pf.machinery', '_launch_audit.py', 554, 'drop_if:554',
     'if machinery_route(held): return False',
     'a machinery call is not proved', 'CONTROLLED',
     'machinery-reached-by-assignment-is-unproved'),
    ('pf.is-a-call', '_launch_audit.py', 556, 'drop_if:556',
     'if isinstance(held, ast.Call):',
     'a name bound to a call is judged on the call', 'CONTROLLED',
     'factory-origin-cannot-be-named-is-unproved'),
    ('pf.getattr', '_launch_audit.py', 557, 'drop_if:557',
     "if normalize(callee_of(held)) == 'getattr': return False",
     'a getattr call is not proved', 'CONTROLLED',
     'getattr-held-receiver-is-unproved'),
    ('pf.origin', '_launch_audit.py', 568, 'drop_stmt:568',
     'return origin in safe_names and origin not in bound',
     'a call is proved when the analyser can name what it calls',
     'CONTROLLED',
     'factory-origin-cannot-be-named-is-unproved'),
    # pf.origin-not-bound: see ARM_NOTES in _launch_arm_records.
    ('pf.origin-not-bound', '_launch_audit.py', 568, 'boolop:568:1',
     'return origin in safe_names and origin not in bound',
     'the `origin not in bound` half of that same return',
     'CONTROLLED',
     'rebound-module-name-called-bare-is-unplaced'),
    ('pf.fallthrough', '_launch_audit.py', 569, 'drop_stmt:569',
     'return True', 'a name bound to no call is proved', 'CONTROLLED',
     'proved-name-receiver-is-not-reported'),
    ('ub.not-bounded', '_launch_audit.py', 588, 'drop_if:588',
     "if not any(keyword.arg == 'timeout' or keyword.arg is None for key...",
     'a call with no timeout= and no ** unpack is not in scope',
     'CONTROLLED',
     'conditional-class-body-attribute-is-reported'),
    ('ub.receiver', '_launch_audit.py', 591, 'replace:591:receiver = func',
     'receiver = func.value if isinstance(func, ast.Attribute) else func',
     'the receiver is the attribute value or the func', 'CONTROLLED',
     'call-on-a-name-the-analyser-can-name-is-still-proved'),
    ('ub.unproved', '_launch_audit.py', 592, 'drop_if:592',
     'if not proved_fixed(receiver): return True',
     'an unproved bounded call is reported unplaced', 'CONTROLLED',
     'alias-import-unplaced'),
    ('sink.gate', '_launch_audit.py', 596, 'drop_if:596',
     'if bound_sink is not None: placed = {id(node) for node in...',
     'the sink is filled only when a caller asked', 'CONTROLLED',
     'alias-import-unplaced'),
    ('sink.no-launch', '_launch_audit.py', 602, 'drop_if:602',
     'if not launches: refusals.append(',
     'a module with no visible launch is a refusal', 'CONTROLLED',
     'class-attribute-receiver-is-reported'),
    ('pl.unpack', '_launch_audit.py', 619, 'drop_if:619',
     'if None in keywords: refusals.append(',
     'a **-unpacked mapping is a refusal and a site', 'CONTROLLED',
     'unpack-at-a-non-git-launch'),
    ('pl.timeout', '_launch_audit.py', 626, 'drop_if:626',
     "if 'timeout' in keywords: refusals.append(",
     'a timeout= is a refusal and a site', 'CONTROLLED', 'ambiguous-name'),
    ('pl.foreign-keyword', '_launch_audit.py', 635, 'drop_if:635',
     'if foreign: # A keyword the stdlib rejects is a `TypeError` at run...',
     'a keyword the stdlib does not take is a refusal and a site',
     'CONTROLLED', 'foreign-keyword-on-a-launch'),
    ('pl.check', '_launch_audit.py', 647, 'drop_if:647',
     'if not (isinstance(check, ast.Constant) and check.value is True):...',
     'a launch that does not check=True is a refusal', 'CONTROLLED',
     'launch-without-check'),
    ('pl.not-run', '_launch_audit.py', 651, 'drop_if:651',
     "if isinstance(node.func, ast.Attribute) \\ and node.func.attr != 'r...",
     'a launch through anything but .run is a refusal', 'CONTROLLED',
     'launch-through-check-output'),
    ('pl.argv-unreadable', '_launch_audit.py', 659, 'drop_if:659',
     'if container is None: refusals.append(',
     'an argv the reader cannot resolve is refused', 'CONTROLLED',
     'argv-not-a-list-literal'),
    ('pl.non-git', '_launch_audit.py', 663, 'drop_if:663',
     "if words and words[0] != 'git': interpreter = (container is not No...",
     'a non-git head is a refusal', 'CONTROLLED', 'head-not-the-git-constant'),
    ('pl.interpreter', '_launch_audit.py', 666, 'drop_if:666',
     'if not interpreter: refusals.append(',
     'a sys.executable head is not a non-git refusal', 'CONTROLLED',
     'head-not-the-git-constant'),
    ('pl.clone', '_launch_audit.py', 670, 'drop_if:670',
     "if words and words[0] == 'git' and 'clone' in words: declared = {w...",
     'a git clone is checked for its silencing configs', 'CONTROLLED',
     'clone-without-advice.detachedHead'),
    ('pl.clone-missing', '_launch_audit.py', 676, 'drop_if:676',
     'if missing: refusals.append(',
     'a missing silencing config is a refusal', 'CONTROLLED',
     'clone-without-advice.detachedHead'),
    ('rc.constant', '_argv_read.py', 55, 'drop_if:55',
     'if isinstance(element, ast.Constant) \\ and isinstance(element.valu...',
     'a string constant resolves to itself', 'CONTROLLED',
     'argv-container-is-git-when-any-element-is'),
    ('rc.guard', '_argv_read.py', 58, 'drop_if:58',
     'if not (isinstance(element, ast.Name) and element.id in self.bindi...',
     'anything but a readable, unheld, unambiguous, unseen name is None',
     'CONTROLLED',
     'argv-container-is-git-when-any-element-is'),
    ('rc.follow', '_argv_read.py', 63, 'drop_stmt:63',
     'seen.add(element.id) element = self.binding_map[element.id]',
     'a name in scope is followed one hop', 'REDUNDANT',
     ('`ARGV_UNWRAP_CAP` at _argv_read.py:26: `seen` can fire only on a name '
      'the flat loop visits twice, which in a name-to-value table is a '
      'cycle, and a cycle is unbounded so the cap answers the same None '
      'first')),
    ('ra.binop', '_argv_read.py', 85, 'drop_if:85',
     'if isinstance(expr, ast.BinOp) and isinstance(expr.op, ast.Add): e...',
     'a + chain is unwrapped from the left', 'CONTROLLED',
     'a-concat-argv-is-unwrapped-from-the-left'),
    ('ra.name-guard', '_argv_read.py', 90, 'drop_if:90',
     'if expr.id in seen or expr.id in self.ambiguous \\ or expr.id not i...',
     'a seen, ambiguous or unheld name makes the argv unreadable',
     'CONTROLLED', 'ambiguous-name'),
    ('ra.follow', '_argv_read.py', 93, 'drop_stmt:93',
     'seen.add(expr.id) expr = self.binding_map[expr.id]',
     'a name in scope is followed one hop', 'REDUNDANT',
     ('`ARGV_UNWRAP_CAP` at _argv_read.py:26, as `rc.follow`: a cycle ends '
      'at the cap, which returns the same None the :90 guard returns')),
    ('ra.list', '_argv_read.py', 96, 'drop_if:96',
     'if isinstance(expr, (ast.List, ast.Tuple)): return expr',
     'a literal list/tuple is the argv', 'CONTROLLED',
     'argv-container-is-git-when-any-element-is'),
    ('ra.else', '_argv_read.py', 98, 'drop_stmt:98', 'return None',
     'any other expression is not an argv', 'REDUNDANT',
     ("the loop's own `return None` at _argv_read.py:99: deleting :98 leaves "
      'the same expression re-tested until the cap answers the same None')),
    ('ha.binop', '_argv_read.py', 111, 'drop_if:111',
     'if isinstance(expr, ast.BinOp) and isinstance(expr.op, ast.Add): e...',
     'a + chain is unwrapped from the left', 'CONTROLLED',
     'a-concat-into-the-ambiguity-walk-is-ambiguous'),
    ('ha.name-guard', '_argv_read.py', 115, 'drop_if:115',
     'if expr.id in seen or expr.id not in self.binding_map:',
     'a seen or unheld name ends the walk without ambiguity', 'CONTROLLED',
     'an-unheld-argv-name-ends-the-ambiguity-walk'),
    ('ha.ambiguous', '_argv_read.py', 117, 'drop_if:117',
     'if expr.id in self.ambiguous: return True',
     'a name bound twice makes the head ambiguous', 'CONTROLLED',
     'ambiguous-name'),
    ('ha.follow', '_argv_read.py', 119, 'drop_stmt:119',
     'seen.add(expr.id) expr = self.binding_map[expr.id]',
     'a name in scope is followed one hop', 'REDUNDANT',
     ('`ARGV_UNWRAP_CAP` at _argv_read.py:26, as `rc.follow`: a cycle '
      'reaches :123 `return False`, which is what :115 returns first')),
    ('ha.else', '_argv_read.py', 122, 'drop_stmt:122', 'return False',
     'any other expression ends the walk', 'REDUNDANT',
     "the loop's own `return False` at _argv_read.py:123, as `ra.else`"),
    ('rw.no-container', '_argv_read.py', 127, 'drop_if:127',
     'if container is None: return []', 'no container means no words',
     'CONTROLLED', 'ambiguous-name'),
    ('rw.words', '_argv_read.py', 129, 'drop_stmt:129',
     'return [self.resolve_constant(element) for element in...',
     'a container reads element-wise', 'CONTROLLED',
     'clone-without-advice.detachedHead'),
    ('ii.sys-executable', '_argv_read.py', 134, 'replace:134:return False',
     'return (isinstance(element, ast.Attribute)',
     'a literal sys.executable is recognised', 'CONTROLLED',
     'sys-executable-head-is-a-non-git-head'),
    ('fw.empty', '_argv_read.py', 147, 'drop_if:147',
     'if container is None or not container.elts: return (None, containe...',
     'a container with no elements is unreadable', 'CONTROLLED',
     'argv-with-no-elements-is-a-non-git-head'),
    ('fw.interpreter', '_argv_read.py', 150, 'drop_if:150',
     'if self.is_interpreter(first): return (None, True)',
     'a sys.executable head is a readable non-git', 'CONTROLLED',
     'sys-executable-head-is-a-non-git-head'),
    ('fw.resolve', '_argv_read.py', 152, 'drop_stmt:152',
     'value = self.resolve_constant(first) return (value, value is not...',
     'any other head resolves as a constant', 'CONTROLLED',
     'a-clean-launch-emits-nothing'),
    ('hl.no-container', '_argv_read.py', 164, 'drop_if:164',
     "if container is None: return 'unreadable'",
     'no container is an unreadable head', 'CONTROLLED', 'ambiguous-name'),
    ('hl.container', '_argv_read.py', 166, 'drop_if:166',
     'if container.elts and isinstance(container.elts[0], (ast.List, ast...',
     'a container of argvs is git if any is', 'CONTROLLED',
     'argv-container-is-git-when-any-element-is'),
    ('hl.git', '_argv_read.py', 172, 'drop_if:172',
     "if first_value == 'git': return 'git'",
     "a head that reads 'git' is a git head", 'CONTROLLED',
     'argv-container-is-git-when-any-element-is'),
    ('hl.non-git', '_argv_read.py', 174, 'drop_stmt:174',
     "return 'non-git' if first_readable else 'unreadable'",
     'a readable non-git head is labelled non-git', 'CONTROLLED',
     'unpack-at-a-non-git-launch'),
    ('rs.binop', '_argv_read.py', 195, 'drop_if:195',
     'if isinstance(element, ast.BinOp) \\ and isinstance(element.op, ast...',
     'a + concat folds when both sides read', 'CONTROLLED',
     'import-module-name-from-a-concat'),
    ('rs.constant', '_argv_read.py', 200, 'drop_if:200',
     'if isinstance(element, ast.Constant) \\ and isinstance(element.valu...',
     'a string constant resolves to itself', 'CONTROLLED',
     'exec-namespace-receiver-is-placed'),
    ('rs.guard', '_argv_read.py', 203, 'drop_if:203',
     'if not (isinstance(element, ast.Name) and element.id in self.bindi...',
     'a non-name, unheld, ambiguous or self-fed name resolves to nothing',
     'CONTROLLED',
     'import-module-name-concat-with-a-non-string'),
    ('rs.follow', '_argv_read.py', 214, 'drop_stmt:214',
     'seen.add(element.id) element = self.binding_map[element.id]',
     'a name in scope is followed one hop', 'CONTROLLED',
     'self-referential-concat-name'),
)
