#!/usr/bin/env python3
"""Daedalus bridge CLI — drive the browser extension from a shell.

Configuration comes from the environment:
  DAEDALUS_URL    bridge base URL (default: http://127.0.0.1:8081)
  DAEDALUS_TOKEN  bridge token, as generated by the extension on install
  TOKEN           one-off override for DAEDALUS_TOKEN
  ID              target tab id (optional — omit to broadcast to every tab)

An embedding application may instead put a module named `_settings` on
sys.path exposing `setting(name, default)` and `required(name)`; when one is
importable it takes over configuration lookup, so a deployment can serve these
values from its own store rather than the process environment. Nothing here
depends on that: with no such module the environment is the only source.
"""
import argparse, json, os, sys, time, urllib.request, urllib.error, urllib.parse

from . import __version__

try:
    # Optional embedding hook: an application may put a `_settings` module on
    # sys.path to serve configuration from its own store. It is absent by
    # design in a plain install, which is exactly what the except covers.
    from _settings import setting, required  # pyright: ignore[reportMissingImports]
except ImportError:                       # bundle not installed — env only
    def setting(name, default=None):
        return os.environ.get(name) or default

    def required(name, hint=''):
        v = os.environ.get(name)
        if not v:
            raise SystemExit(f"{name} is not set (export it)")
        return v

URL = setting('DAEDALUS_URL', 'http://127.0.0.1:8081')


def token():
    # TOKEN is the one-off override; DAEDALUS_TOKEN is the durable one, and it
    # goes through `required` so an embedding _settings module can serve it from
    # a store instead. Resolving it here rather than at import time is what lets
    # a shell, a scheduled job and a long-lived session all work the same way.
    return os.environ.get('TOKEN') or required('DAEDALUS_TOKEN')


def tab():
    return os.environ.get('ID', '')


# ─── HTTP helpers ───

def _query_path(path, params):
    """Build one bridge path with every query value percent-encoded."""
    query = urllib.parse.urlencode(params)
    return f'{path}?{query}' if query else path


def api(method, path, body=None):
    url = URL + path
    data = json.dumps(body).encode() if body else None
    headers = {'Content-Type': 'application/json'} if data else {}
    req = urllib.request.Request(url, data=data, headers=headers, method=method)
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            return json.loads(r.read())
    except urllib.error.HTTPError as e:
        try:
            err = json.loads(e.read())
        except Exception:
            err = e.read().decode()
        sys.exit(f'HTTP {e.code}: {err}')
    except urllib.error.URLError as e:
        sys.exit(f'Connection failed: {e.reason}')


def api_raw(method, path):
    """Like api() but returns raw bytes instead of JSON."""
    url = URL + path
    req = urllib.request.Request(url, method=method)
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            return r.read()
    except urllib.error.HTTPError as e:
        sys.exit(f'HTTP {e.code}')
    except urllib.error.URLError as e:
        sys.exit(f'Connection failed: {e.reason}')


def api_delete(path, body):
    """Send DELETE request with JSON body."""
    url = URL + path
    data = json.dumps(body).encode()
    req = urllib.request.Request(url, data=data, headers={'Content-Type': 'application/json'}, method='DELETE')
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            return json.loads(r.read())
    except urllib.error.HTTPError as e:
        try:
            err = json.loads(e.read())
        except Exception:
            err = e.read().decode()
        sys.exit(f'HTTP {e.code}: {err}')
    except urllib.error.URLError as e:
        sys.exit(f'Connection failed: {e.reason}')


def wait_for_result(cmd_id, target_tab, delivery_id, timeout, interval=0.5):
    """Return the result for one command delivery, or None on timeout.

    The PUT response's delivery id distinguishes this invocation from a stale
    result with the same command id. Conditional consume names the generation
    just peeked, so a newer result that replaces it remains for its owner.
    """
    params = {'token': token()}
    if target_tab:
        params['tab'] = target_tab
    t0 = time.time()
    while time.time() - t0 < timeout:
        time.sleep(interval)
        res = api('GET', _query_path('/result', params))
        if res.get('pending'):
            continue
        if (res.get('id') != cmd_id
                or res.get('deliveryId') != delivery_id):
            continue  # another caller's result — leave it in place for them
        generation = res.get('resultGeneration')
        if not generation:
            continue
        consumed = api('GET', _query_path('/result', {
            **params, 'consume': '1', 'expected': generation}))
        if (consumed.get('consumed') is not True
                or consumed.get('resultGeneration') != generation):
            continue
        return res
    return None


# ─── Result display ───

def validate_result(res):
    """Check result JSON has expected fields, warn on missing."""
    expected = {'id', 'result', 'error', 'ts', 'token'}
    missing = expected - set(res.keys())
    if missing:
        print(f'⚠ Missing fields: {", ".join(sorted(missing))}', file=sys.stderr)
    if 'id' in res and not isinstance(res['id'], str):
        print(f'⚠ id is {type(res["id"]).__name__}, expected str', file=sys.stderr)


def _format_eval_world(world):
    """Present the wire `world` value only as an execution channel."""
    return f'channel={world}'


def print_result(res, raw=False):
    if raw:
        print(json.dumps(res, indent=2, ensure_ascii=False))
        return

    validate_result(res)

    hdr = f'← {res.get("id", "?")}'
    t = res.get('tabId', '')
    world = res.get('world', '')
    ms = res.get('exec_ms')
    if t:
        hdr += f'  tab={t[:12]}'
    if world:
        hdr += f'  @{_format_eval_world(world)}'
    if isinstance(ms, (int, float)):
        hdr += f'  {ms}ms'

    err = res.get('error')
    if err:
        print(f'{hdr}  ERROR: {err}')
        sys.exit(1)

    print(hdr)
    r = res.get('result')
    if isinstance(r, (dict, list)):
        print(json.dumps(r, indent=2, ensure_ascii=False))
    elif r is not None:
        print(r)
    else:
        print('(undefined)')


# ─── Command dispatch core ───

def send_and_wait(cmd_id, code, target_tab, wait, timeout):
    if not cmd_id:
        sys.exit('Command ID is required')
    if not code:
        sys.exit('Code is empty')
    if not isinstance(cmd_id, str):
        sys.exit(f'Command ID must be a string, got {type(cmd_id).__name__}')

    payload = {'token': token(), 'id': cmd_id, 'code': code}
    if target_tab:
        payload['tab'] = target_tab

    resp = api('PUT', '/command', payload)
    target = resp.get('target', '?')
    print(f'→ {cmd_id} → {target}  ({len(code)} bytes)')

    if not wait:
        return

    res = wait_for_result(cmd_id, target_tab, resp.get('did'), timeout)
    if res is None:
        sys.exit(f'Timeout ({timeout}s) — no result received')
    print_result(res)


# ─── Subcommands ───

def do_tabs(args):
    tabs = api('GET', _query_path('/tabs', {'token': token()}))
    if getattr(args, 'json', False):
        print(json.dumps(tabs or [], indent=2))
        return
    if not tabs:
        print('No active tabs')
        return
    for t in sorted(tabs, key=lambda x: x.get('age', 0)):
        tid = t['tabId']
        age = t.get('age', '?')
        url = t.get('url', '')
        title = t.get('title', '')[:50]
        print(f'  {tid}  {age:>4}s  {title:<50}  {url}')


def do_put(args):
    if args.file == '-':
        code = sys.stdin.read()
    else:
        if not os.path.isfile(args.file):
            sys.exit(f'File not found: {args.file}')
        with open(args.file, encoding='utf-8') as f:
            code = f.read()
    target_tab = '' if args.broadcast else tab()
    send_and_wait(args.id, code.strip(), target_tab,
                  wait=not args.no_result, timeout=args.timeout)


def do_exec(args):
    target_tab = '' if args.broadcast else tab()
    send_and_wait(args.id, args.code.strip(), target_tab,
                  wait=not args.no_result, timeout=args.timeout)


def do_result(args):
    params = {'token': token()}
    t = tab()
    if t:
        params['tab'] = t
    if args.consume:
        params['consume'] = '1'
    res = api('GET', _query_path('/result', params))
    if res.get('pending'):
        print('No result pending')
        return
    print_result(res, raw=args.raw)


def do_ping(args):
    target_tab = tab()
    t0 = time.time()
    payload = {'token': token(), 'id': '_ping', 'code': 'document.title'}
    if target_tab:
        payload['tab'] = target_tab
    sent = api('PUT', '/command', payload)

    res = wait_for_result(
        '_ping', target_tab, sent.get('did'), 10, interval=0.3)
    if res is None:
        sys.exit('Ping timeout (10s)')
    err = res.get('error')
    if err:
        sys.exit(f'Ping error: {err}')
    ms = (time.time() - t0) * 1000
    title = res.get('result', '')
    world = res.get('world', '')
    loc = f'@{_format_eval_world(world)}' if world else ''
    print(f'Pong {loc}: "{title}"  ({ms:.0f}ms)')


def do_navigate(args):
    target_tab = tab()
    code = f'location.href = {json.dumps(args.url)}'
    send_and_wait('_nav', code, target_tab, wait=False, timeout=0)


def do_reload(args):
    target_tab = '' if args.broadcast else tab()
    send_and_wait('_reload', 'location.reload()', target_tab,
                  wait=False, timeout=0)


def do_title(args):
    target_tab = tab()
    send_and_wait('_title', 'document.title', target_tab,
                  wait=True, timeout=10)


def do_url(args):
    target_tab = tab()
    send_and_wait('_url', 'location.href', target_tab,
                  wait=True, timeout=10)


def do_segment_job(args):
    # Minting is idempotent for the owning token, so this both creates a job
    # and re-fetches its capability. The printed sig substitutes for __SIG__
    # in examples/hls-segment-relay.js; it authorizes segment writes to this
    # one job only, which is why the relay script never needs the bridge token.
    res = api('POST', '/segment-job', {'token': token(), 'job': args.job})
    print(res['sig'])


def do_segment_status(args):
    # /segment-status takes the job-scoped capability, not the bridge token.
    # The capability is only handed out by POST /segment-job, which MINTS the
    # job when it does not exist yet (idempotent for the owning token) — so a
    # status query for a mistyped name creates that job as a side effect.
    req = urllib.request.Request(
        f'{URL}/segment-job',
        data=json.dumps({'token': token(), 'job': args.job}).encode(),
        headers={'Content-Type': 'application/json'}, method='POST')
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            sig = json.loads(r.read())['sig']
    except urllib.error.HTTPError as e:
        if e.code == 409:
            sys.exit(f'segment-status: job "{args.job}" is owned by a different token')
        try:
            err = json.loads(e.read())
        except Exception:
            err = e.read().decode()
        sys.exit(f'HTTP {e.code}: {err}')
    except urllib.error.URLError as e:
        sys.exit(f'Connection failed: {e.reason}')
    res = api('GET', _query_path(
        '/segment-status', {'job': args.job, 'sig': sig}))
    count = res.get('count', 0)
    done = res.get('done', [])
    print(f'Job: {args.job}  Segments: {count}')
    if done:
        full = set(range(min(done), max(done) + 1))
        gaps = sorted(full - set(done))
        if gaps:
            print(f'Gaps ({len(gaps)}): {gaps[:30]}{"..." if len(gaps) > 30 else ""}')
        else:
            print(f'Complete: {min(done)}–{max(done)}')


# ─── Extension command helper ───

def ext_cmd(cmd_id, cmd_type, timeout=10, **fields):
    """Send an extension command and wait for result. Returns result dict or exits on error."""
    cmd = {'id': cmd_id, 'type': cmd_type, 'token': token(), 'tab': 'extension', **fields}
    sent = api('PUT', '/command', cmd)
    res = wait_for_result(cmd_id, 'extension', sent.get('did'), timeout)
    if res is None:
        sys.exit(f'Timeout ({timeout}s)')
    if res.get('error'):
        sys.exit(f'Error: {res["error"]}')
    return res.get('result', {})


# ─── Extension commands (screenshot, cookies, cdp, uploads) ───

def do_screenshot(args):
    """Send screenshot command to extension, wait for upload, optionally save to local file."""
    cmd = {'token': token(), 'id': args.id or '_ss', 'code': '', 'tab': 'extension'}
    cmd_payload = {'id': cmd['id'], 'type': 'screenshot'}
    if args.format:
        cmd_payload['format'] = args.format
    if args.quality:
        cmd_payload['quality'] = args.quality
    if args.chrome_tab:
        cmd_payload['tabId'] = int(args.chrome_tab)

    resp = api('PUT', '/command', {**cmd_payload, 'token': token(), 'tab': 'extension'})
    print(f'→ screenshot → {resp.get("target", "?")}')

    timeout = args.timeout or 15
    res = wait_for_result(
        cmd['id'], 'extension', resp.get('did'), timeout)
    if res is None:
        sys.exit(f'Timeout ({timeout}s)')
    if res.get('error'):
        sys.exit(f'Screenshot error: {res["error"]}')
    result = res.get('result', {})
    path = result.get('path', '')
    size = result.get('size', 0)
    print(f'← uploaded: {path} ({size} bytes)')
    # Optionally save locally
    if args.output:
        ss_url = _query_path(
            '/screenshot', {'token': token(), 'id': cmd['id']})
        img = api_raw('GET', ss_url)
        with open(args.output, 'wb') as f:
            f.write(img)
        print(f'Saved to {args.output}')


def do_cookies(args):
    """Get cookies for a domain via extension."""
    cmd = {'id': '_cookies', 'type': 'cookies', 'token': token(), 'tab': 'extension'}
    if args.domain:
        cmd['domain'] = args.domain
    if args.url:
        cmd['url'] = args.url
    sent = api('PUT', '/command', cmd)
    res = wait_for_result('_cookies', 'extension', sent.get('did'), 10)
    if res is None:
        sys.exit('Timeout (10s)')
    if res.get('error'):
        sys.exit(f'Cookie error: {res["error"]}')
    cookies = res.get('result', [])
    if args.raw:
        print(json.dumps(cookies, indent=2, ensure_ascii=False))
    else:
        for c in cookies:
            print(f'  {c.get("domain", "")}  {c.get("name", "")}={c.get("value", "")}')
    print(f'{len(cookies)} cookies')


def do_set_cookie(args):
    """Set a cookie via extension."""
    cmd = {'id': '_set_cookie', 'type': 'set-cookie', 'token': token(), 'tab': 'extension',
           'url': args.url, 'name': args.name, 'value': args.value}
    if args.domain: cmd['domain'] = args.domain
    if args.path: cmd['path'] = args.path
    if args.http_only: cmd['httpOnly'] = True
    if args.secure: cmd['secure'] = True
    if args.same_site: cmd['sameSite'] = args.same_site
    if args.expires: cmd['expirationDate'] = float(args.expires)
    sent = api('PUT', '/command', cmd)
    res = wait_for_result(
        '_set_cookie', 'extension', sent.get('did'), 10)
    if res is None:
        sys.exit('Timeout (10s)')
    if res.get('error'):
        sys.exit(f'Error: {res["error"]}')
    print(f'Set: {args.name}={args.value[:60]} on {args.url}')


def do_remove_cookie(args):
    """Remove a specific cookie via extension."""
    cmd = {'id': '_rm_cookie', 'type': 'remove-cookie', 'token': token(), 'tab': 'extension',
           'url': args.url, 'name': args.name}
    sent = api('PUT', '/command', cmd)
    res = wait_for_result(
        '_rm_cookie', 'extension', sent.get('did'), 10)
    if res is None:
        sys.exit('Timeout (10s)')
    if res.get('error'):
        sys.exit(f'Error: {res["error"]}')
    print(f'Removed: {args.name} from {args.url}')


def do_clear_cookies(args):
    """Clear all cookies for a domain via extension."""
    cmd = {'id': '_clear_cookies', 'type': 'clear-cookies', 'token': token(), 'tab': 'extension'}
    if args.domain: cmd['domain'] = args.domain
    if args.url: cmd['url'] = args.url
    sent = api('PUT', '/command', cmd)
    res = wait_for_result(
        '_clear_cookies', 'extension', sent.get('did'), 10)
    if res is None:
        sys.exit('Timeout (10s)')
    if res.get('error'):
        sys.exit(f'Error: {res["error"]}')
    removed = res.get('result', {}).get('removed', 0)
    print(f'Cleared {removed} cookies')


def do_cdp(args):
    """Send raw CDP command via extension."""
    params = json.loads(args.params) if args.params else {}
    cmd = {'id': '_cdp', 'type': 'cdp', 'method': args.method, 'params': params,
           'token': token(), 'tab': 'extension'}
    if args.chrome_tab:
        cmd['tabId'] = args.chrome_tab
    if args.keep_session:
        cmd['keep_session'] = True
    sent = api('PUT', '/command', cmd)
    res = wait_for_result('_cdp', 'extension', sent.get('did'), 30)
    if res is None:
        sys.exit('Timeout (30s)')
    print_result(res, raw=args.raw)


def do_close_tab(args):
    """Close one or more Chrome tabs via extension."""
    ids = [int(x) for x in args.chrome_tabs]
    cmd: dict = {'id': '_close_tab', 'type': 'close-tab', 'token': token(), 'tab': 'extension'}
    if len(ids) == 1:
        cmd['tabId'] = ids[0]
    else:
        cmd['tabIds'] = ids
    sent = api('PUT', '/command', cmd)
    res = wait_for_result(
        '_close_tab', 'extension', sent.get('did'), 10)
    if res is None:
        sys.exit('Timeout (10s)')
    if res.get('error'):
        sys.exit(f'Error: {res["error"]}')
    result = res.get('result', {})
    closed = result.get('closed', [])
    errs = result.get('errors', [])
    if closed:
        print(f'Closed {len(closed)} tab(s): {closed}')
    for e in errs:
        print(f'Failed tab {e.get("id", "?")}: {e.get("error", "")}')
    if not closed and not errs:
        print('No tabs affected')


def do_fetch_timings(args):
    """Fetch the background fetch-relay timing ring buffer."""
    fields = {}
    if args.reset:
        fields['reset'] = True
    result = ext_cmd('_fetch_timings', 'fetch-timings', **fields)
    timings = result.get('timings', [])
    count = result.get('count', 0)
    has_native = result.get('hasNativeToBase64', False)
    print(f'Fetch timings: {count} entries  nativeToBase64={has_native}')
    if args.raw:
        print(json.dumps(timings, indent=2, ensure_ascii=False))
        return
    if not timings:
        print('(empty)')
        return
    # Print tail of N entries with columns
    tail = timings[-args.n:]
    print(f'{"method":6} {"status":6} {"size":>10} {"decode":>8} {"fetch":>8} {"encode":>8} {"total":>8}  url')
    for t in tail:
        if 'error' in t:
            print(f'{t.get("method", ""):6} {"ERR":6} {"":>10} {"":>8} {"":>8} {"":>8} {t.get("ms_total", ""):>8}  {t.get("url", "")[:80]} ({t["error"]})')
        else:
            size_mb = t.get('bodySize', 0) / 1024 / 1024
            print(f'{t.get("method", ""):6} {t.get("status", ""):6} {size_mb:>9.2f}M {t.get("ms_bodyDecode", ""):>8} {t.get("ms_fetch", ""):>8} {t.get("ms_encode", ""):>8} {t.get("ms_total", ""):>8}  {t.get("url", "")[:80]}')
    # Summary stats
    completed = [t for t in timings if 'error' not in t]
    if completed:
        import statistics
        totals = [t['ms_total'] for t in completed]
        fetches = [t['ms_fetch'] for t in completed]
        encodes = [t['ms_encode'] for t in completed]
        print(f'\n{len(completed)} successful: total median={statistics.median(totals):.0f}ms mean={statistics.mean(totals):.0f}ms '
              f'fetch median={statistics.median(fetches):.0f}ms encode median={statistics.median(encodes):.0f}ms')


def do_ext_self_reload(args):
    """Reload the extension from disk via chrome.runtime.reload()."""
    result = ext_cmd('_ext_reload', 'ext-reload')
    print(f'Extension reloading from v{result.get("version", "?")} — will reconnect SSE automatically')


def do_open_tab(args):
    """Open a new tab via extension."""
    fields = {'url': args.url}
    if args.background:
        fields['active'] = False
    if args.pinned:
        fields['pinned'] = True
    result = ext_cmd('_open_tab', 'open-tab', **fields)
    print(f'Opened tab {result.get("tabId", "?")} → {args.url}')


def do_open_tabs(args):
    """Open multiple tabs in one extension round-trip."""
    fields: dict = {'urls': list(args.urls)}
    if args.background:
        fields['active'] = False
    if args.pinned:
        fields['pinned'] = True
    result = ext_cmd('_open_tabs', 'open-tabs', timeout=30, **fields)
    opened = result.get('opened', [])
    errors = result.get('errors', [])
    for o in opened:
        print(f'Opened tab {o.get("tabId", "?")} → {o.get("url", "")}')
    for e in errors:
        print(f'FAILED {e.get("url", "?")}: {e.get("error", "")}')
    print(f'{len(opened)} opened, {len(errors)} failed')


def do_focus_tab(args):
    """Focus a Chrome tab via extension."""
    result = ext_cmd('_focus', 'focus-tab', tabId=int(args.chrome_tab))
    print(f'Focused tab {result.get("tabId", "?")} window={result.get("windowId", "?")}')


def do_ext_navigate(args):
    """Navigate a tab to URL via extension (works on any page including chrome://)."""
    fields = {'url': args.url}
    if args.chrome_tab:
        fields['tabId'] = int(args.chrome_tab)
    result = ext_cmd('_nav', 'navigate', **fields)
    print(f'Navigated tab {result.get("tabId", "?")} → {args.url}')


def do_ext_reload(args):
    """Reload a tab via extension."""
    fields = {}
    if args.chrome_tab:
        fields['tabId'] = int(args.chrome_tab)
    if args.bypass_cache:
        fields['bypassCache'] = True
    result = ext_cmd('_reload', 'reload', **fields)
    print(f'Reloaded tab {result.get("tabId", "?")}' + (' (bypass cache)' if args.bypass_cache else ''))


def do_inject_css(args):
    """Inject CSS into a tab via extension."""
    if args.file:
        with open(args.file, encoding='utf-8') as f:
            css = f.read()
    else:
        css = args.css
    fields: dict = {'css': css}
    if args.chrome_tab:
        fields['tabId'] = int(args.chrome_tab)
    if args.all_frames:
        fields['allFrames'] = True
    result = ext_cmd('_inject_css', 'inject-css', **fields)
    print(f'Injected {result.get("injected", "?")} chars CSS into tab {result.get("tabId", "?")}')


def do_remove_css(args):
    """Remove injected CSS from a tab via extension."""
    if args.file:
        with open(args.file, encoding='utf-8') as f:
            css = f.read()
    else:
        css = args.css
    fields: dict = {'css': css}
    if args.chrome_tab:
        fields['tabId'] = int(args.chrome_tab)
    if args.all_frames:
        fields['allFrames'] = True
    result = ext_cmd('_remove_css', 'remove-css', **fields)
    print(f'Removed {result.get("removed", "?")} chars CSS from tab {result.get("tabId", "?")}')


def do_block_requests(args):
    """Block page requests matching a URL pattern via extension."""
    cmd = {'id': '_block', 'type': 'block-requests', 'token': token(), 'tab': 'extension',
           'pattern': args.pattern}
    if args.chrome_tab:
        cmd['tabId'] = int(args.chrome_tab)
    sent = api('PUT', '/command', cmd)
    res = wait_for_result('_block', 'extension', sent.get('did'), 10)
    if res is None:
        sys.exit('Timeout (10s)')
    if res.get('error'):
        sys.exit(f'Error: {res["error"]}')
    result = res.get('result', {})
    print(f'Blocked: {result.get("pattern", "")}  ruleId={result.get("ruleId", "")}  tabs={result.get("tabIds", [])}')


def do_unblock_requests(args):
    """Remove block rules via extension."""
    cmd: dict = {'id': '_unblock', 'type': 'unblock-requests', 'token': token(), 'tab': 'extension'}
    if args.rule_id:
        cmd['ruleId'] = int(args.rule_id)
    sent = api('PUT', '/command', cmd)
    res = wait_for_result('_unblock', 'extension', sent.get('did'), 10)
    if res is None:
        sys.exit('Timeout (10s)')
    if res.get('error'):
        sys.exit(f'Error: {res["error"]}')
    removed = res.get('result', {}).get('removed', [])
    print(f'Removed {len(removed)} rule(s): {removed}')


def do_list_block_rules(args):
    """List active block rules via extension."""
    cmd = {'id': '_list_rules', 'type': 'list-block-rules', 'token': token(), 'tab': 'extension'}
    sent = api('PUT', '/command', cmd)
    res = wait_for_result(
        '_list_rules', 'extension', sent.get('did'), 10)
    if res is None:
        sys.exit('Timeout (10s)')
    if res.get('error'):
        sys.exit(f'Error: {res["error"]}')
    rules = res.get('result', [])
    if not rules:
        print('No active block rules')
        return
    for r in rules:
        cond = r.get('condition', {})
        print(f'  id={r["id"]}  pattern={cond.get("urlFilter", "")}  tabs={cond.get("tabIds", "all")}')
    print(f'{len(rules)} rule(s)')


def do_uploads(args):
    """List or delete uploads."""
    if args.delete:
        body = {'token': token()}
        if args.id:
            body['id'] = args.id
        if args.filename:
            body['filename'] = args.filename
        api_delete('/upload', body)
        print('Deleted')
        return
    params = {'token': token()}
    if args.id:
        params['id'] = args.id
    files = api('GET', _query_path('/upload', params))
    if not files:
        print('No uploads')
        return
    for f in files:
        ts = time.strftime('%Y-%m-%d %H:%M', time.localtime(f.get('mtime', 0)))
        print(f'  {f["id"]}/{f["filename"]}  {f["size"]:>8} bytes  {ts}')
    print(f'{len(files)} files')


def do_net_capture(args):
    """Start network capture on a Chrome tab via CDP."""
    fields = {}
    if args.chrome_tab:
        fields['tabId'] = int(args.chrome_tab)
    if args.max:
        fields['maxRequests'] = args.max
    result = ext_cmd('_net_cap', 'net-capture', timeout=15, **fields)
    if result.get('already'):
        print(f'Already capturing on tab {result.get("tabId")} ({result.get("buffered", 0)} requests buffered)')
    else:
        print(f'Capturing network on tab {result.get("tabId")}')


def do_net_capture_stop(args):
    """Stop network capture and dump results."""
    fields = {}
    if args.chrome_tab:
        fields['tabId'] = int(args.chrome_tab)
    if args.bodies:
        fields['bodies'] = True
    result = ext_cmd('_net_stop', 'net-capture-stop', timeout=30, **fields)
    if not result.get('stopped'):
        print(f'Not capturing: {result.get("reason", "?")}')
        return
    requests = result.get('requests', [])
    if args.raw:
        print(json.dumps(result, indent=2, ensure_ascii=False))
        return
    print(f'Captured {len(requests)} requests from tab {result.get("tabId")}')
    for r in requests:
        status = r.get('status', '???')
        method = r.get('method', '?')
        url = r.get('url', '')[:120]
        rtype = r.get('type', '')
        print(f'  {status} {method} {rtype:<12} {url}')


def do_net_capture_get(args):
    """Get current network capture buffer."""
    fields = {}
    if args.chrome_tab:
        fields['tabId'] = int(args.chrome_tab)
    if args.filter:
        fields['filter'] = args.filter
    if args.bodies:
        fields['bodies'] = True
    result = ext_cmd('_net_get', 'net-capture-get', timeout=30, **fields)
    requests = result.get('requests', [])
    if args.raw:
        print(json.dumps(result, indent=2, ensure_ascii=False))
        return
    print(f'{len(requests)} requests on tab {result.get("tabId")}')
    for r in requests:
        status = r.get('status', '???')
        method = r.get('method', '?')
        url = r.get('url', '')[:120]
        rtype = r.get('type', '')
        print(f'  {status} {method} {rtype:<12} {url}')


def do_store_hotfix(args):
    """Store a hotfix in the extension."""
    if args.file and os.path.isfile(args.file):
        with open(args.file, encoding='utf-8') as f:
            code = f.read()
    else:
        code = args.file  # treat as inline code
    result = ext_cmd('_store_hf', 'store-hotfix', fixId=args.fix_id, code=code, permanent=args.permanent)
    perm = ' [PERM]' if result.get('permanent') else ''
    print(f'Stored hotfix "{result.get("stored", "?")}"{perm} ({result.get("total", "?")} total)')


def do_clear_hotfix(args):
    """Clear a specific hotfix from the extension."""
    result = ext_cmd('_clear_hf', 'clear-hotfix', fixId=args.fix_id)
    found = result.get('found', False)
    print(f'Cleared hotfix "{result.get("cleared", "?")}" (found={found}, remaining={result.get("remaining", 0)})')


def do_clear_hotfixes(args):
    """Clear all hotfixes from the extension."""
    result = ext_cmd('_clear_all_hf', 'clear-all-hotfixes', includePermanent=args.include_permanent)
    if args.include_permanent:
        print('All hotfixes cleared (incl. permanent)')
    else:
        kept = result.get('kept', 0)
        removed = result.get('removed', 0)
        print(f'Cleared {removed} hotfix(es); {kept} permanent kept')


def do_list_hotfixes(args):
    """List all stored hotfixes."""
    result = ext_cmd('_list_hf', 'list-hotfixes')
    fixes = result.get('fixes', [])
    if not fixes:
        print('No hotfixes stored')
        return
    print(f'Version: {result.get("version", "?")}')
    for hf in fixes:
        ts = time.strftime('%Y-%m-%d %H:%M', time.localtime(hf.get('ts', 0) / 1000))
        code_preview = hf['code'][:80].replace('\n', '\\n')
        marker = '[PERM]' if hf.get('permanent') else '      '
        print(f'  {marker} {hf["id"]}  {ts}  {code_preview}')
    print(f'{len(fixes)} hotfix(es)')


def do_set_permanent(args):
    """Toggle the permanent flag on an existing hotfix."""
    val = args.permanent.lower() in ('true', '1', 'yes', 'y', 'on')
    result = ext_cmd('_set_perm', 'set-permanent', fixId=args.fix_id, permanent=val)
    found = result.get('found', False)
    if not found:
        sys.exit(f'No hotfix with id "{args.fix_id}"')
    print(f'Set permanent={val} on "{args.fix_id}"')


# ─── Argument parser ───

def main():
    for _stream in (sys.stdout, sys.stderr):
        try:
            # TextIO has no reconfigure in the stub; the real stdout usually
            # does, and the except below is what handles the case where the
            # stream is a pipe that does not.
            _stream.reconfigure(  # pyright: ignore[reportAttributeAccessIssue]
                encoding="utf-8", errors="replace")
        except (AttributeError, ValueError, OSError):
            pass  # not a reconfigurable stream (redirected/piped)
    p = argparse.ArgumentParser(
        prog='daedalus',
        description='Daedalus bridge CLI',
        epilog='Env: DAEDALUS_TOKEN (bridge token), ID (tab id, optional), '
               'DAEDALUS_URL (default http://127.0.0.1:8081)',
    )
    p.add_argument('--version', action='version',
                   version=f'daedalus {__version__}')
    sub = p.add_subparsers(dest='cmd', required=True)

    # tabs
    p_tabs = sub.add_parser('tabs', help='List active tabs')
    p_tabs.add_argument('--json', action='store_true',
                        help='Emit JSON array of tab objects')

    # put
    s = sub.add_parser('put', help='Send JS file as command')
    s.add_argument('id', help='Command ID')
    s.add_argument('file', help='JS file path (or - for stdin)')
    s.add_argument('--no-result', action='store_true', help="Don't wait for result")
    s.add_argument('-b', '--broadcast', action='store_true', help='Send to all tabs (ignore ID)')
    s.add_argument('-t', '--timeout', type=int, default=15, help='Result timeout seconds (default 15)')

    # exec
    s = sub.add_parser('exec', help='Send inline JS code')
    s.add_argument('id', help='Command ID')
    s.add_argument('code', help='JS code string')
    s.add_argument('--no-result', action='store_true', help="Don't wait for result")
    s.add_argument('-b', '--broadcast', action='store_true', help='Send to all tabs (ignore ID)')
    s.add_argument('-t', '--timeout', type=int, default=15, help='Result timeout seconds (default 15)')

    # result
    s = sub.add_parser('result', help='Fetch latest result')
    s.add_argument('-c', '--consume', action='store_true', help='Delete result after reading')
    s.add_argument('--raw', action='store_true', help='Print raw JSON')

    # ping
    sub.add_parser('ping', help='Test round-trip to tab')

    # navigate
    s = sub.add_parser('navigate', help='Navigate tab to URL')
    s.add_argument('url', help='Target URL')

    # reload
    sub.add_parser('reload', help='Reload tab page')

    # title
    sub.add_parser('title', help='Get tab document.title')

    # url
    sub.add_parser('url', help='Get tab location.href')

    # segment-job
    s = sub.add_parser('segment-job', help='Mint (or re-fetch) the HLS segment capability for a job and print it')
    s.add_argument('job', help='Job name')

    # segment-status
    s = sub.add_parser('segment-status', help='HLS segment job status')
    s.add_argument('job', help='Job name')

    # screenshot (extension)
    s = sub.add_parser('screenshot', help='Capture screenshot via extension')
    s.add_argument('--id', default='_ss', help='Command ID (default _ss)')
    s.add_argument('-o', '--output', help='Save screenshot to local file')
    s.add_argument('-f', '--format', choices=['png', 'jpeg'], help='Image format (default png)')
    s.add_argument('-q', '--quality', type=int, help='JPEG quality (1-100)')
    s.add_argument('--chrome-tab', help='Chrome tab ID (default: active tab)')
    s.add_argument('-t', '--timeout', type=int, default=15, help='Timeout seconds')

    # cookies (extension)
    s = sub.add_parser('cookies', help='Get cookies via extension')
    s.add_argument('-d', '--domain', help='Filter by domain')
    s.add_argument('-u', '--url', help='Filter by URL')
    s.add_argument('--raw', action='store_true', help='Print full JSON (no truncation)')

    # set-cookie (extension)
    s = sub.add_parser('set-cookie', help='Set a cookie via extension')
    s.add_argument('url', help='URL for the cookie (e.g. https://example.com)')
    s.add_argument('name', help='Cookie name')
    s.add_argument('value', help='Cookie value')
    s.add_argument('-d', '--domain', help='Cookie domain')
    s.add_argument('--path', help='Cookie path')
    s.add_argument('--http-only', action='store_true', help='HttpOnly flag')
    s.add_argument('--secure', action='store_true', help='Secure flag')
    s.add_argument('--same-site', choices=['no_restriction', 'lax', 'strict'], help='SameSite policy')
    s.add_argument('--expires', help='Expiration as Unix timestamp')

    # remove-cookie (extension)
    s = sub.add_parser('remove-cookie', help='Remove a specific cookie')
    s.add_argument('url', help='URL for the cookie')
    s.add_argument('name', help='Cookie name')

    # clear-cookies (extension)
    s = sub.add_parser('clear-cookies', help='Clear all cookies for a domain')
    s.add_argument('-d', '--domain', help='Domain to clear')
    s.add_argument('-u', '--url', help='URL to clear')

    # cdp (extension)
    s = sub.add_parser('cdp', help='Send raw CDP command via extension')
    s.add_argument('method', help='CDP method (e.g. Page.captureScreenshot)')
    s.add_argument('-p', '--params', help='JSON params string')
    s.add_argument('--chrome-tab', help='Chrome tab ID')
    s.add_argument('--keep-session', action='store_true',
                   help='Hold the chrome.debugger session after this call (for Profiler.enable/start/stop, HeapProfiler, Tracing)')
    s.add_argument('--raw', action='store_true', help='Print raw JSON')

    # fetch-timings (extension diagnostics)
    s = sub.add_parser('fetch-timings', help='Fetch background fetch-relay timing ring buffer')
    s.add_argument('-n', type=int, default=30, help='Show last N entries (default 30)')
    s.add_argument('--reset', action='store_true', help='Clear ring buffer after reading')
    s.add_argument('--raw', action='store_true', help='Print raw JSON')

    # ext-self-reload (extension)
    sub.add_parser('ext-self-reload', help='Reload extension from disk (chrome.runtime.reload)')

    # open-tab (extension)
    s = sub.add_parser('open-tab', help='Open a new tab via extension')
    s.add_argument('url', help='URL to open')
    s.add_argument('--background', action='store_true', help='Open in background (inactive)')
    s.add_argument('--pinned', action='store_true', help='Pin the tab')

    # open-tabs (extension)
    s = sub.add_parser('open-tabs', help='Open many tabs in one round-trip')
    s.add_argument('urls', nargs='+', help='URLs to open')
    s.add_argument('--background', action='store_true', help='Open in background (inactive)')
    s.add_argument('--pinned', action='store_true', help='Pin the tabs')

    # focus-tab (extension)
    s = sub.add_parser('focus-tab', help='Focus a Chrome tab via extension')
    s.add_argument('chrome_tab', help='Chrome tab ID to focus')

    # ext-navigate (extension)
    s = sub.add_parser('ext-navigate', help='Navigate tab to URL via extension (works on chrome:// pages)')
    s.add_argument('url', help='Target URL')
    s.add_argument('--chrome-tab', help='Chrome tab ID (default: active tab)')

    # ext-reload (extension)
    s = sub.add_parser('ext-reload', help='Reload tab via extension (supports cache bypass)')
    s.add_argument('--chrome-tab', help='Chrome tab ID (default: active tab)')
    s.add_argument('--bypass-cache', action='store_true', help='Bypass cache on reload')

    # close-tab (extension)
    s = sub.add_parser('close-tab', help='Close Chrome tab(s) via extension')
    s.add_argument('chrome_tabs', nargs='+', help='Chrome tab ID(s) to close')

    # inject-css (extension)
    s = sub.add_parser('inject-css', help='Inject CSS into a tab')
    g = s.add_mutually_exclusive_group(required=True)
    g.add_argument('--css', help='CSS string to inject')
    g.add_argument('--file', help='CSS file to inject')
    s.add_argument('--chrome-tab', help='Chrome tab ID (default: active tab)')
    s.add_argument('--all-frames', action='store_true', help='Inject into all frames')

    # remove-css (extension)
    s = sub.add_parser('remove-css', help='Remove injected CSS from a tab')
    g = s.add_mutually_exclusive_group(required=True)
    g.add_argument('--css', help='CSS string to remove (must match injected)')
    g.add_argument('--file', help='CSS file to remove')
    s.add_argument('--chrome-tab', help='Chrome tab ID (default: active tab)')
    s.add_argument('--all-frames', action='store_true', help='Remove from all frames')

    # block-requests (extension)
    s = sub.add_parser('block-requests', help='Block page requests matching a URL pattern')
    s.add_argument('pattern', help='URL filter pattern (e.g. "*.cdn.example.com/vod/*/seg-*")')
    s.add_argument('--chrome-tab', help='Restrict to specific Chrome tab ID')

    # unblock-requests (extension)
    s = sub.add_parser('unblock-requests', help='Remove block rules')
    s.add_argument('--rule-id', help='Specific rule ID to remove (default: all)')

    # list-block-rules (extension)
    sub.add_parser('list-block-rules', help='List active block rules')

    # net-capture (extension)
    s = sub.add_parser('net-capture', help='Start CDP network capture on a tab')
    s.add_argument('--chrome-tab', help='Chrome tab ID (default: active)')
    s.add_argument('--max', type=int, default=1000, help='Max requests to buffer (default: 1000)')

    # net-capture-stop (extension)
    s = sub.add_parser('net-capture-stop', help='Stop network capture and dump results')
    s.add_argument('--chrome-tab', help='Chrome tab ID (default: active)')
    s.add_argument('--bodies', action='store_true', help='Fetch response bodies before stopping')
    s.add_argument('--raw', action='store_true', help='Print raw JSON')

    # net-capture-get (extension)
    s = sub.add_parser('net-capture-get', help='Get current network capture buffer')
    s.add_argument('--chrome-tab', help='Chrome tab ID (default: active)')
    s.add_argument('--filter', help='Regex filter on URL or type')
    s.add_argument('--bodies', action='store_true', help='Fetch response bodies')
    s.add_argument('--raw', action='store_true', help='Print raw JSON')

    # store-hotfix (extension)
    s = sub.add_parser('store-hotfix', help='Store a persistent hotfix in the extension')
    s.add_argument('fix_id', help='Hotfix identifier')
    s.add_argument('file', help='JS file path or inline code')
    s.add_argument('--permanent', action='store_true', help='Mark fix as permanent (survives extension version bumps)')

    # clear-hotfix (extension)
    s = sub.add_parser('clear-hotfix', help='Remove a specific hotfix')
    s.add_argument('fix_id', help='Hotfix identifier to remove')

    # clear-hotfixes (extension)
    s = sub.add_parser('clear-hotfixes', help='Remove all hotfixes (permanents skipped by default)')
    s.add_argument('--include-permanent', action='store_true', help='Also remove permanent hotfixes')

    # list-hotfixes (extension)
    sub.add_parser('list-hotfixes', help='List stored hotfixes')

    # set-permanent (extension)
    s = sub.add_parser('set-permanent', help='Toggle the permanent flag on an existing hotfix')
    s.add_argument('fix_id', help='Hotfix identifier')
    s.add_argument('permanent', help='true|false (or 1|0, yes|no)')

    # uploads
    s = sub.add_parser('uploads', help='List or delete uploads')
    s.add_argument('--id', help='Filter by upload ID')
    s.add_argument('--filename', help='Specific filename (for delete)')
    s.add_argument('--delete', action='store_true', help='Delete instead of list')

    args = p.parse_args()

    dispatch = {
        'tabs': do_tabs,
        'put': do_put,
        'exec': do_exec,
        'result': do_result,
        'ping': do_ping,
        'navigate': do_navigate,
        'reload': do_reload,
        'title': do_title,
        'url': do_url,
        'segment-job': do_segment_job,
        'segment-status': do_segment_status,
        'screenshot': do_screenshot,
        'cookies': do_cookies,
        'set-cookie': do_set_cookie,
        'remove-cookie': do_remove_cookie,
        'clear-cookies': do_clear_cookies,
        'cdp': do_cdp,
        'fetch-timings': do_fetch_timings,
        'ext-self-reload': do_ext_self_reload,
        'open-tab': do_open_tab,
        'open-tabs': do_open_tabs,
        'focus-tab': do_focus_tab,
        'ext-navigate': do_ext_navigate,
        'ext-reload': do_ext_reload,
        'close-tab': do_close_tab,
        'inject-css': do_inject_css,
        'remove-css': do_remove_css,
        'block-requests': do_block_requests,
        'unblock-requests': do_unblock_requests,
        'list-block-rules': do_list_block_rules,
        'net-capture': do_net_capture,
        'net-capture-stop': do_net_capture_stop,
        'net-capture-get': do_net_capture_get,
        'store-hotfix': do_store_hotfix,
        'clear-hotfix': do_clear_hotfix,
        'clear-hotfixes': do_clear_hotfixes,
        'list-hotfixes': do_list_hotfixes,
        'set-permanent': do_set_permanent,
        'uploads': do_uploads,
    }
    dispatch[args.cmd](args)


if __name__ == '__main__':
    main()
