"""Where the bridge is, who we are to it, and every request that reaches it.

Configuration comes from the environment:
  DAEDALUS_URL    bridge base URL (default: http://127.0.0.1:8081)
  DAEDALUS_TOKEN  bridge token, as generated by the extension on install
  TOKEN           one-off override for DAEDALUS_TOKEN
  ID              target tab id (optional — omit to broadcast to every tab)

An embedding application may instead put a module named `_settings` on
sys.path exposing `setting(name, default)` and `required(name)`; when one is
importable it takes over configuration lookup, so a deployment can serve these
values from its own store rather than the process environment. Nothing here
depends on that: with no such module the environment is the only source.
"""
import argparse
import json
import os
import sys
import time
import urllib.error
import urllib.parse
import urllib.request


try:
    # Optional embedding hook: an application may put a `_settings` module on
    # sys.path to serve configuration from its own store. It is absent by
    # design in a plain install, which is exactly what the except covers.
    from _settings import setting, required  # pyright: ignore[reportMissingImports]
except ImportError:                       # bundle not installed — env only
    def setting(name, default=None):
        return os.environ.get(name) or default

    def required(name, hint=''):
        v = os.environ.get(name)
        if not v:
            raise SystemExit(f"{name} is not set (export it)")
        return v

URL = setting('DAEDALUS_URL', 'http://127.0.0.1:8081')


def token():
    # TOKEN is the one-off override; DAEDALUS_TOKEN is the durable one, and it
    # goes through `required` so an embedding _settings module can serve it from
    # a store instead. Resolving it here rather than at import time is what lets
    # a shell, a scheduled job and a long-lived session all work the same way.
    return os.environ.get('TOKEN') or required('DAEDALUS_TOKEN')


def tab():
    return os.environ.get('ID', '')


NET_CAPTURE_MAX = 20000


def capture_limit(value):
    """argparse type for --max: a capture buffer is a memory budget.

    It lives in the service worker and grows to hold headers and response
    bodies, so a nonpositive value produced a buffer that evicts its only
    event and an enormous one produced no bound at all. The ceiling matches
    NET_CAPTURE_MAX in extension/background.js, which enforces it again on
    arrival — a caller is not the only thing that can send this field.
    """
    try:
        limit = int(value)
    except ValueError:
        raise argparse.ArgumentTypeError(
            f'--max must be an integer from 1 to {NET_CAPTURE_MAX}; '
            f'got {value!r}') from None
    if limit < 1 or limit > NET_CAPTURE_MAX:
        raise argparse.ArgumentTypeError(
            f'--max must be an integer from 1 to {NET_CAPTURE_MAX}; got {limit}')
    return limit


def positive_timeout(value):
    """argparse type for a result wait.

    A negative wait is worse than a rejected one: the command is PUT to the
    bridge first and the deadline is only checked afterwards, so the poll
    loop runs zero times, the caller is told it timed out, and the browser
    goes on to execute the command anyway. Retrying after that report runs
    the side effect twice. Rejecting the value at parse time means nothing
    has been admitted yet.

    Zero is accepted and keeps the meaning it already has at every call
    site: `args.timeout or <default>` reads it as "unset".
    """
    try:
        seconds = int(value)
    except ValueError:
        raise argparse.ArgumentTypeError(
            f'timeout must be a whole number of seconds; got {value!r}') from None
    if seconds < 0:
        raise argparse.ArgumentTypeError(
            f'timeout must not be negative; got {seconds}')
    return seconds


def _query_path(path, params):
    """Build one bridge path with every query value percent-encoded."""
    query = urllib.parse.urlencode(params)
    return f'{path}?{query}' if query else path


def _http_error_detail(e):
    """The body of a failed response, JSON-decoded when it is JSON.

    An HTTPError body can only be read once. Reading it inside the JSON
    attempt and again in the fallback left the fallback with an empty
    string, so a front end answering with a plain-text page was reported as
    a status and nothing else.
    """
    raw = e.read()
    try:
        return json.loads(raw)
    except Exception:
        return raw.decode(errors='replace')


def api(method, path, body=None, timeout=30, headers=None):
    url = URL + path
    data = json.dumps(body).encode() if body else None
    # The bridge decides credentials before it reads a body, so the token goes
    # in a header too. Without it a request larger than the bridge's
    # unauthenticated window is refused before its body is read at all. It is
    # also what keeps a reusable credential out of the request target, where
    # every proxy access log would keep it.
    headers = dict(headers or {}, **{'Authorization': f'Bearer {token()}'})
    if data:
        headers['Content-Type'] = 'application/json'
    req = urllib.request.Request(url, data=data, headers=headers, method=method)
    try:
        with urllib.request.urlopen(req, timeout=timeout) as r:
            return json.loads(r.read())
    except urllib.error.HTTPError as e:
        sys.exit(f'HTTP {e.code}: {_http_error_detail(e)}')
    except urllib.error.URLError as e:
        sys.exit(f'Connection failed: {e.reason}')


def api_raw(method, path):
    """Like api() but returns raw bytes instead of JSON."""
    url = URL + path
    req = urllib.request.Request(
        url, method=method, headers={'Authorization': f'Bearer {token()}'})
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            return r.read()
    except urllib.error.HTTPError as e:
        sys.exit(f'HTTP {e.code}: {_http_error_detail(e)}')
    except urllib.error.URLError as e:
        sys.exit(f'Connection failed: {e.reason}')


def api_delete(path, body):
    """Send DELETE request with JSON body."""
    url = URL + path
    data = json.dumps(body).encode()
    req = urllib.request.Request(
        url, data=data, method='DELETE',
        headers={'Content-Type': 'application/json',
                 'Authorization': f'Bearer {token()}'})
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            return json.loads(r.read())
    except urllib.error.HTTPError as e:
        sys.exit(f'HTTP {e.code}: {_http_error_detail(e)}')
    except urllib.error.URLError as e:
        sys.exit(f'Connection failed: {e.reason}')


def wait_for_result(cmd_id, target_tab, delivery_id, timeout, interval=0.5):
    """Return the result for one command delivery, or None on timeout.

    The PUT response's delivery id distinguishes this invocation from a stale
    result with the same command id. Conditional consume names the generation
    just peeked, so a newer result that replaces it remains for its owner.

    The wait ramps 20ms -> `interval` instead of sleeping `interval` up front:
    most commands finish in tens of milliseconds, and the fixed first sleep
    charged half a second of dead time to every command that waited, however
    fast the result actually landed. The ramp keeps a slot that stays pending
    from becoming a request flood, which is what a flat short interval would
    be. Same shape as the MCP poller, for the same reason.
    """
    params = {}
    if target_tab:
        params['tab'] = target_tab
    if delivery_id:
        params['delivery'] = delivery_id
    # One monotonic deadline for the whole wait, and every blocking step is
    # capped by what is left of it. The loop used to check the clock only
    # before each iteration and then give each HTTP call its own fixed 30s,
    # so a single stalled poll ran far past the timeout the caller asked for
    # — a 50ms wait returned after 320ms against one 300ms stall. Wall-clock
    # time.time() also went backwards under an NTP step; monotonic does not.
    deadline = time.monotonic() + timeout
    wait = 0.02
    while True:
        remaining = deadline - time.monotonic()
        if remaining <= 0:
            return None
        time.sleep(min(wait, remaining))
        wait = min(wait * 2, interval)
        remaining = deadline - time.monotonic()
        if remaining <= 0:
            return None
        res = api('GET', _query_path('/result', params), timeout=remaining)
        if res.get('pending'):
            continue
        result_delivery_id = res.get('deliveryId')
        if (res.get('id') != cmd_id
                or not delivery_id
                or not result_delivery_id
                or result_delivery_id != delivery_id):
            continue  # another caller's result — leave it in place for them
        generation = res.get('resultGeneration')
        if not generation:
            continue
        # The consume is what actually claims the result, so it is allowed to
        # finish: giving up here would leave a result nobody takes. It is
        # still bounded, by the ordinary request timeout.
        consumed = api('GET', _query_path('/result', {
            **params, 'consume': '1', 'expected': generation}))
        if (consumed.get('consumed') is not True
                or consumed.get('resultGeneration') != generation):
            continue
        return res
